# name: Deploy Infrastructure

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   terraform:
#     name: Terraform
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Google Cloud
#         uses: google-github-actions/setup-gcloud@v0.2.0
#         with:
#           version: "latest"
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Terraform Init
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: "1.0.0"
#           terraform_wrapper: false

#       - name: Terraform Format
#         run: terraform fmt -check

#       - name: Terraform Plan
#         id: plan
#         run: terraform plan

#         # Se desejar ver os detalhes do plano Terraform nos comentários do pull request,
#         # você pode descomentar e configurar a step abaixo:
#         # - name: Comment PR with Terraform Plan result
#         #   if: github.event_name == 'pull_request'
#         #   uses: actions/github-script@v3
#         #   with:
#         #     github-token: ${{ secrets.GITHUB_TOKEN }}
#         #     script: |
#         #       const output = `Terraform plan output:\n\`\`\`${{ steps.plan.outputs.stdout }}\`\`\``;
#         #       github.issues.createComment({
#         #         issue_number: context.issue.number,
#         #         owner: context.repo.owner,
#         #         repo: context.repo.repo,
#         #         body: output
#         #       });

#       - name: Terraform Apply
#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#         run: terraform apply -auto-approve
#         env:
#           TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
#           # Defina outras variáveis de ambiente necessárias para o Terraform aqui

name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Check and Run SQL Script
        env:
          CONNECTION_NAME: ${{ secrets.DB_CONNECTION_NAME }}
          USER: ${{ secrets.DB_USER }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DB_NAME }}
          TF_VAR_postgres_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_postgres_username: ${{ secrets.DB_USER }}
        run: bash ./scripts/check_and_run_sql.sh $CONNECTION_NAME $USER $PASSWORD $DATABASE_NAME
